const DATA_DIR = "$(pkgdir(PrecipitationAnalysis))/data/"
const PRECIPITATION_DATA_FILEPATH = DATA_DIR*"precipitation/"
const STATIONS_SERIALIZED_FILEPATH = DATA_DIR*"lista_estaciones.jls"
const SHAPEFILES_PATH = DATA_DIR*"shape_files"
const TIME_DENSITIES_FILEPATH = DATA_DIR*"time_densities.jls"